kind: pipeline
type: kubernetes # Note, it's where your runners run.
name: default

# steps:
# - name: install
#   image: python:3.12-slim
#   commands:
#   - pip install -r requirements.txt

steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: dockersock
        path: /var/run
    settings:
      repo: 192.168.49.2:5000/fstack-be
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
      registry: 192.168.49.2:5000
      insecure: true
    when:
      event: [push]

services:
  - name: helper
    image: alpine:3
    volumes:
      - name: docker-daemon-json
        path: /etc/docker/daemon.json
    command: ["sh", "-c", 'echo ''{"insecure-registries":["192.168.49.2:5000"]}'' > /etc/docker/daemon.json']

  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
      - name: docker-daemon-json
        path: /etc/docker/daemon.json

volumes:
  - name: dockersock
    temp: {}
  - name: docker-daemon-json
    temp: {}
